# For QD visualization and metrics.
# In the case of cma-mae, also provides x0 in case of restart.
qd_archive:
  _target_: ribs.archives.GridArchive
  dims: [100, 100]
  ranges: [[0,1], [0,1]]
  learning_rate: 0.1
  threshold_min: 1e-6 # obj=0 means infeasible environment; do not add
  seed: ${seed}

# For saving all results found throughout the search.
# This is needed because QD archive implements elitism and may discard past results if better alternatives are found.
logging_archive:
  _target_: src.myribs.archives.LoggingArchive
  starting_cells: ${oc.mul:2, ${oc.add:${collect_embedding_num_evals}, ${env_search_num_evals}}} # 2 * evaluation budget to make sure hashing succeeds
  threshold_min: 1e-6 # obj=0 means infeasible environment; do not add

emitter:
  # _target_: src.myribs.emitters.EvolutionStrategyEmitterExternal
  _target_: ribs.emitters.EvolutionStrategyEmitter
  sigma0: 0.02
  batch_size: 8
  seed: ${seed}

scheduler:
  # _target_: src.myribs.schedulers.SchedulerExternal
  _target_: src.myribs.schedulers.BanditSchedulerExternal
  num_active: 1
  zeta: 0.5
  reselect: all