defaults:
  - /eval@eval: no_measure
  - _self_

archive:
  _target_: src.myribs.archives.LoggingArchive
  starting_cells: ${oc.mul:2, ${oc.add:${collect_embedding_num_evals}, ${env_search_num_evals}}} # 2 * evaluation budget to make sure hashing succeeds

emitter:
  _target_: src.myribs.emitters.FixedGaussianEmitter
  sigma: 0.02
  batch_size: ${oc.env_int:NUM_SERVERS}

scheduler:
  _target_: src.myribs.schedulers.SchedulerExternal