archive:
  _target_: ribs.archives.GridArchive
  dims: [100, 100]
  ranges: [[0,1], [0,1]]
  learning_rate: 0.1
  threshold_min: 0
  seed: ${seed}

emitter:
  # _target_: src.myribs.emitters.EvolutionStrategyEmitterExternal
  _target_: ribs.emitters.EvolutionStrategyEmitter
  sigma0: 0.02
  batch_size: 8
  seed: ${seed}

scheduler:
  # _target_: src.myribs.schedulers.SchedulerExternal
  _target_: src.myribs.schedulers.BanditSchedulerExternal
  num_active: 2
  zeta: 0.5