defaults:
  - envgen: domain_randomization
  - eval: first_timestep
  - _self_

hydra:
  run:
    dir: ./outputs/${hydra:runtime.choices.qd}/${hydra:runtime.choices.eval}/${now:%Y-%m-%d_%H%M%S}

dataset_dir: ${hydra:runtime.output_dir}/embeddings
dataset_size: 1000
seed: 42

single_process: ${oc.env_isone:NUM_SERVERS}