
task_ids: [2,7]

task_eval:
  _target_: src.libero_spatial_eval.LiberoSpatialEval
  num_trials_per_sol: ${oc.env_int:NUM_SERVERS}
  max_steps: 220
  num_steps_wait: 10
  replan_steps: 5
  seed: ${seed}
  repair_config:
    time_limit: 1500
    seed: ${seed}
  camera_heights: 256
  camera_widths: 256