task_ids: [0,1,2,3,4,5,6,7,8,9]

task_eval:
  _target_: src.libero_spatial_eval.LiberoSpatialEval
  objective_func: entropy
  measure_func: spread_similarity
  num_trials_per_sol: ${oc.env_int:NUM_SERVERS}
  max_steps: 220
  num_steps_wait: 10
  replan_steps: 5
  server_port_start: ${oc.env_int:SERVER_PORT_START}
  seed: ${seed}
  repair_config:
    time_limit: 1500
    seed: ${seed}
  camera_heights: 256
  camera_widths: 256