task_ids: [0,1,2,3,4,5,6,7,8,9]

task_eval:
  _target_: src.libero_spatial_eval.LiberoSpatialEval
  objective_func: adversarial
  measure_func: spread_similarity
  num_trials_per_sol: ${oc.len:${.vla_server_uris}}
  max_steps: 220
  num_steps_wait: 10
  replan_steps: 5
  vla_server_uris: ${oc.env_csv:VLA_SERVER_URIs}
  seed: ${seed}
  repair_config:
    time_limit: 1500
    seed: ${seed}
  camera_heights: 256
  camera_widths: 256